item {
    name: "Friz C"
    id: 1
}

item {
    name: "Marvelon"
    id: 2
}

item {
    name: "M.V. Poly S.C"
    id: 3
}

item {
    name: "Salol et Menthol Mixture"
    id: 4
}

item {
    name: "Mercilon"
    id: 5
}

item {
    name: "Flora"
    id: 6
}

item {
    name: "Brand"
    id: 7
}

item {
    name: "Ventolin"
    id: 8
}

item {
    name: "Flora Cap"
    id: 9
}

item {
    name: "Koolfever"
    id: 10
}

item {
    name: "Gaviscon"
    id: 11
}

item {
    name: "Haemovit"
    id: 12
}

item {
    name: "Postinor"
    id: 13
}

item {
    name: "PEI PA KOA"
    id: 14
}

item {
    name: "SMOOTHE"
    id: 15
}

item {
    name: "YEAO PAYA BRAND BALM"
    id: 16
}

item {
    name: "Neobun"
    id: 17
}

item {
    name: "marimer"
    id: 18
}

item {
    name: "Meliane ED"
    id: 19
}

item {
    name: "Benlo"
    id: 20
}

item {
    name: "Boxing Liniment"
    id: 21
}

item {
    name: "Somthawin Yellow Oil"
    id: 22
}

item {
    name: "Septyl"
    id: 23
}

item {
    name: "P.M. Glove"
    id: 24
}

item {
    name: "Srichand"
    id: 25
}

item {
    name: "MIRACID"
    id: 26
}

item {
    name: "CHOMJAI"
    id: 27
}

item {
    name: "Brown mixture"
    id: 28
}

item {
    name: "Strepsils honey & Lemon"
    id: 29
}

item {
    name: "Lilly"
    id: 30
}

item {
    name: "Oilezz"
    id: 31
}

item {
    name: "Mybacin"
    id: 32
}

item {
    name: "YAz"
    id: 33
}

item {
    name: "KAO-KUI WATER"
    id: 34
}

item {
    name: "Dechamp"
    id: 35
}

item {
    name: "Strepsils CHESTY COUGH"
    id: 36
}

item {
    name: "PREME"
    id: 37
}

item {
    name: "SUCEE"
    id: 38
}

item {
    name: "Ayura"
    id: 39
}

item {
    name: "New born"
    id: 40
}

item {
    name: "pen park"
    id: 41
}

item {
    name: "Madonna"
    id: 42
}

item {
    name: "Hista-Oph"
    id: 43
}

item {
    name: "Gano speck 500"
    id: 44
}

item {
    name: "Sara strawberry"
    id: 45
}

item {
    name: "Hircudoid Mucopolysaccharide"
    id: 46
}

item {
    name: "Gastro bismol 524"
    id: 47
}

item {
    name: "ladompon"
    id: 48
}

item {
    name: "Anna Oral Contraceptive"
    id: 49
}

item {
    name: "Tensoplast"
    id: 50
}

item {
    name: "Hyles 25"
    id: 51
}

item {
    name: "Blendera-MF"
    id: 52
}

item {
    name: "sodum witayasom"
    id: 53
}

item {
    name: "yakom namtaothong"
    id: 54
}

item {
    name: "tiger balm"
    id: 55
}

item {
    name: "Neo rub"
    id: 56
}

item {
    name: "Tomcin"
    id: 57
}

item {
    name: "pim saen balm oil roll"
    id: 58
}

item {
    name: "moh me satree"
    id: 59
}

item {
    name: "Zema Cream"
    id: 60
}

item {
    name: "YOKI RADIAN POWDER"
    id: 61
}

item {
    name: "CLINICAL THERMOMETER"
    id: 62
}

item {
    name: "Mida B"
    id: 63
}

item {
    name: "Hashi Nasal"
    id: 64
}

item {
    name: "WHITE MONKEY HOLDING PEACH BALM"
    id: 65
}

item {
    name: "Flying snakes"
    id: 66
}

item {
    name: "Yahom pow five pagodas"
    id: 67
}

item {
    name: "pim saen balm oil"
    id: 68
}

item {
    name: "Koolfever Cool Baby"
    id: 69
}

item {
    name: "BRAND Quality Of life"
    id: 70
}

item {
    name: "Normal saline L.P."
    id: 71
}

item {
    name: "Amoxi T.O. 500"
    id: 72
}

item {
    name: "Smoothe White baby face"
    id: 73
}

item {
    name: "gaviscon suspension"
    id: 74
}

item {
    name: "Sara blister"
    id: 75
}

item {
    name: "Flemex Kidse"
    id: 76
}

item {
    name: "PARACAP 500"
    id: 77
}

item {
    name: "Sara Orange"
    id: 78
}

item {
    name: "Solmax Capsule"
    id: 79
}

item {
    name: "Hotta Plus"
    id: 80
}

item {
    name: "Betadine POVIDONE-IODINE"
    id: 81
}

item {
    name: "34090098"
    id: 82
}

item {
    name: "03010206 	marvelon 28"
    id: 83
}

item {
    name: "40011205  	sara for children 60ml"
    id: 84
}

item {
    name: "23015305	Solmax Capsule 10*25 strips"
    id: 85
}

item {
    name: "35050910	DG1"
    id: 86
}

item {
    name: "31080204	boxing 120ml"
    id: 87
}

item {
    name: "39020205-1	Opsar eye"
    id: 88
}

item {
    name: "06001005	Brabds"
    id: 89
}

item {
    name: "08030403	bisolvon"
    id: 90
}

item {
    name: "88081525	hotta"
    id: 91
}

item {
    name: "11011205-2	 betadine"
    id: 92
}

item {
    name: "06170825	strepsils blister original"
    id: 93
}

item {
    name: "06021507	hiruscar"
    id: 94
}

item {
    name: "70040105	yanut"
    id: 95
}

item {
    name: "36010508	fisherman's"
    id: 96
}

item {
    name: "45040905	pregnancy tast"
    id: 97
}

item {
    name: "31080103-01    siang pure"
    id: 98
}

item {
    name: "09030605	margarat"
    id: 99
}

item {
    name: "07020210	seven seas"
    id: 100
}

item {
    name: "40010160	tiffy"
    id: 101
}

item {
    name: "34010205	vitamin c 1000"
    id: 102
}

item {
    name: "78021305	kamin chan"
    id: 103
}

item {
    name: "06041205	flemex"
    id: 104
}

item {
    name: "19002610	Nipro 26*1"
    id: 105
}

item {
    name: "09051006	strepsils hhs original"
    id: 106
}

item {
    name: "90010124"
    id: 107
}

item {
    name: "34010203	vitamin c patar"
    id: 108
}

item {
    name: "08010205	silke"
    id: 109
}

item {
    name: "28062405-01   white tarm"
    id: 110
}

item {
    name: "40023605	tofago"
    id: 111
}

item {
    name: "09051323	strepsils hhr cool"
    id: 112
}

item {
    name: "31360502	pox109"
    id: 113
}

item {
    name: "03091205	avamigran"
    id: 114
}

item {
    name: "73063020	smooth e"
    id: 115
}

item {
    name: "09010405 fungazol"
    id: 116
}

item {
    name: "71010206   Eleven tigers"
    id: 117
}

item {
    name: "31020305	ya satree"
    id: 118
}

item {
    name: "03101111	nat-c ester 1000mg"
    id: 119
}

item {
    name: "40015104   Difelene 50 mg"
    id: 120
}

item {
    name: "06041105 	Flemex 60ml"
    id: 121
}

item {
    name: "02102106	Johnson baby"
    id: 122
}

item {
    name: "03090205	Maptin syrup 60ml"
    id: 123
}

item {
    name: "03090157	Curam 375mg"
    id: 124
}

item {
    name: "94030505	pan enteral 400g"
    id: 125
}

item {
    name: "03100607	Narural vitamin E 100"
    id: 126
}

item {
    name: "03100609	Narural vitamin E 400"
    id: 127
}

item {
    name: "05036307	TWIN 300CC"
    id: 128
}

item {
    name: "05036305	 TWIN 500CC"
    id: 129
}

item {
    name: "06010105	Nizorol cream 5 g"
    id: 130
}

item {
    name: "06010106	Nizorol cream 10g"
    id: 131
}

item {
    name: "006/033/2-010     Cilest"
    id: 132
}

item {
    name: "06011805	Motilium M"
    id: 133
}

item {
    name: "06012805	Retin A"
    id: 134
}

item {
    name: "06181004	Terumo 5cc"
    id: 135
}

item {
    name: "08012115	Pigeon Classic S"
    id: 136
}

item {
    name: "08012120	Pigeon Classic M"
    id: 137
}

item {
    name: "08012125	Pigeon Classic L"
    id: 138
}

item {
    name: "06061523	Dettol 500ml Replenishing"
    id: 139
}

item {
    name: "08012130 	Pigeon Silicone Nipple Size S"
    id: 140
}

item {
    name: "08012131	Pigeon Classic M 3pieces"
    id: 141
}

item {
    name: "08012132	 Pigeon Classic Size L"
    id: 142
}

item {
    name: "08012206	Pigeon Quality Bottle 110 C"
    id: 143
}

item {
    name: "08040105	 Faire visa 3 condoms"
    id: 144
}

item {
    name: "09010906	 Clobet cream 10g"
    id: 145
}

item {
    name: "09013105	alben albendazole 200 mg 2 tablets"
    id: 146
}

item {
    name: "09015204	Cotren cream 5g"
    id: 147
}

item {
    name: "09015205	Cotren Vaginal Tablets 500mg 1 tablets"
    id: 148
}

item {
    name: "19013025	Oxe Cure Scrub 40g"
    id: 149
}

item {
    name: "09015305	Biotril-S 1500mg"
    id: 150
}

item {
    name: "10012415	Tempra Kids 60ml"
    id: 151
}

item {
    name: "10012418	Tempra Forte 60ml"
    id: 152
}

item {
    name: "06181705	Terumo Medisafe 30 pcs."
    id: 153
}

item {
    name: "10020205	Ngamrahong infusion 30 sachets"
    id: 154
}

item {
    name: "19013005	Nifedipine t20 stada retard 100tablets"
    id: 155
}

item {
    name: "19013011	 Felodipin Stada 5mg 10*1"
    id: 156
}

item {
    name: "03070105	CLARITYNE SYRUP 100ML TH"
    id: 157
}

item {
    name: "20020305	 Betaderm-quad 5g"
    id: 158
}

item {
    name: "20030905	 Ambrolex syrup 60ml"
    id: 159
}

item {
    name: "24040405	Thuanthong 99 300tablets"
    id: 160
}

item {
    name: "24040504	Thuanthong 99 100tablets"
    id: 161
}

item {
    name: "24040905	 Thuanthong 99 80tablets"
    id: 162
}

item {
    name: "24041305	Thuanthong 99 50tablets"
    id: 163
}

item {
    name: "25010515	Ellgy plus 50g."
    id: 164
}

item {
    name: "40012312	 Sofclens narmal saline solution 500 ml"
    id: 165
}

item {
    name: "25010905-1	     KTD Elatic bandage width 3 inc"
    id: 166
}

item {
    name: "28010205	 M-SOFT CREAM 20g"
    id: 167
}

item {
    name: "28010310	 Lymarin Cream 15 g"
    id: 168
}

item {
    name: "28032705	  Melcam 7.5mg 10x10 capsules"
    id: 169
}

item {
    name: "28032805	Matenol 10x10 tablets"
    id: 170
}

item {
    name: "28060205	 KorYor15 40CC"
    id: 171
}

item {
    name: "28060226	 KorYor15 Milky Lotion 50g"
    id: 172
}

item {
    name: "29014509	 Amoxy M.H. 250 mg (60ml)"
    id: 173
}

item {
    name: "29014520	Amoxy M.H. 500mg 50x10capsules"
    id: 174
}

item {
    name: "29014605	Baclosal 20x10tabelts"
    id: 175
}

item {
    name: "29014910	Histica 10mg 10x10tablets"
    id: 176
}

item {
    name: "31020804	Yanam-Van-Chakmodluk Seangchai bhasaj 450ml"
    id: 177
}

item {
    name: "31030306	 Yasatree Buakaew Bara Brand 30capsule"
    id: 178
}

item {
    name: "31030602-1"
    id: 179
}

item {
    name: "31040101	Vanchukmodlook soot 1 250ml"
    id: 180
}

item {
    name: "31080904-01  Alcohol LPSOFF Ethyl 30 ml"
    id: 181
}

item {
    name: "31080906	Calamine Leopard Brand 120ml."
    id: 182
}

item {
    name: "40013300 	 NSS Sodium chloride irrigation 1000ml"
    id: 183
}

item {
    name: "31090906	Flying Rabbit 50ml"
    id: 184
}

item {
    name: "84011305"
    id: 185
}

item {
    name: "85060105	Tip coffee sugar free"
    id: 186
}

item {
    name: "88081105	Fitne herbal capsule 30capsule"
    id: 187
}

item {
    name: "34010106	 I Fen Syrup 60ml"
    id: 188
}

item {
    name: "34090306	 O+plus 120ml"
    id: 189
}

item {
    name: "36020305	 Bosisto eucalyptus oil parrot brand 8.5ml"
    id: 190
}

item {
    name: "36022710	 Jason jujubes Honey Lemon 10tablets"
    id: 191
}

item {
    name: "36022712	Jason jujubes Spicy Orange 10tablets"
    id: 192
}

item {
    name: "36022715	 Jason Menthol Black Cherry"
    id: 193
}

item {
    name: "39010210	 Meixil 500mg 500capsules"
    id: 194
}

item {
    name: "39010510	Proctase-p 500capsules"
    id: 195
}

item {
    name: "40015515	 Preme nobu natural c white 30g"
    id: 196
}

item {
    name: "40015524	Preme nobu natural face from 50g"
    id: 197
}

item {
    name: "40021105	Myoxan50x10tablets"
    id: 198
}

item {
    name: "40022406	 Muflex 60ml"
    id: 199
}

item {
    name: "40025007	Cetrizin syrup 60ml"
    id: 200
}

item {
    name: "40025705	Nuro-B 30x10tablets"
    id: 201
}

item {
    name: "67021005	  Unison ointment 15g"
    id: 202
}

item {
    name: "72051705-1  Genta-Betasone cream 5g"
    id: 203
}

item {
    name: "80010105"
    id: 204
}

item {
    name: "80010804	BOTAN FOIL 100SAC/BOX"
    id: 205
}

item {
    name: "89110105	  senna leaf capsule"
    id: 206
}

item {
    name: "89070810	Moringa Thanyapron 100capsules"
    id: 207
}

item {
    name: "89061005	Tra Catherine chrysanthemum flavour 8sachets"
    id: 208
}

item {
    name: "89030605	 polka foot care 13 g"
    id: 209
}

item {
    name: "89030307  KA Magic Lip 2.2 g"
    id: 210
}

item {
    name: "89030306	 KA Magic Lip Natural Active 2.2 g"
    id: 211
}

item {
    name: "89030305	  KA white foam 50 g"
    id: 212
}

item {
    name: "89030303	 KA white foam 25 g"
    id: 213
}

item {
    name: "89030115	   KA Cream 30 g"
    id: 214
}

item {
    name: "89030107	  KA Cream 7 g"
    id: 215
}

item {
    name: "89013106	Hydrogen peroxide sol 60ml"
    id: 216
}

item {
    name: "89010905-1	   Aromatic ammonia spirit 30ml"
    id: 217
}

item {
    name: "89010806	Gentian violet 30ml"
    id: 218
}

item {
    name: "89010711"
    id: 219
}

item {
    name: "89010305-1     Glycerine of borax vidhysom 15ml"
    id: 220
}

item {
    name: "89010205-1"
    id: 221
}

item {
    name: "88210105	Candix Clotrimazole 15ml"
    id: 222
}

item {
    name: "88160105	Viset-niyom 40g"
    id: 223
}

item {
    name: "88140110-1	   lips care"
    id: 224
}

item {
    name: "88120507     Jintan silver pills"
    id: 225
}

item {
    name: "88100205	 Sliming Herb"
    id: 226
}

item {
    name: "88090105-1"
    id: 227
}

item {
    name: "88080405	  Fitne Herbal infusion green Tea Flavored"
    id: 228
}

item {
    name: "88080255	Fitne Herbal Infusion Chrysanthemum Flavored"
    id: 229
}

item {
    name: "88080205	  fitne herbal infusion 10sachats"
    id: 230
}

item {
    name: "88070205	JAMREE 5sachats"
    id: 231
}

item {
    name: "88070110	JR vittamin-e 15g"
    id: 232
}

item {
    name: "88050205-1"
    id: 233
}

item {
    name: "88050105-1	   Ya Kwad Bai Poh Brand"
    id: 234
}

item {
    name: "87030110-1   NICHIDI 15.3 g"
    id: 235
}

item {
    name: "85040205      P.M. Glove powdered size Small 100pc"
    id: 236
}

item {
    name: "85030205	Collagen coffee 13.5gx10sachets"
    id: 237
}

item {
    name: "08012604	cotton buds tiny V-care"
    id: 238
}

item {
    name: "84010605-1"
    id: 239
}

item {
    name: "84010505-1"
    id: 240
}

item {
    name: "84010207"
    id: 241
}

item {
    name: "84010205-1"
    id: 242
}

item {
    name: "82020205"
    id: 243
}

item {
    name: "82014907	 Glibenclamide 5 mg 50x10 tablets"
    id: 244
}

item {
    name: "82014805	Beeswax GPO 15 g"
    id: 245
}

item {
    name: "82014507	Milk of magnesia 450ml"
    id: 246
}

item {
    name: "82014505	 Milk of magnesia 240ml"
    id: 247
}

item {
    name: "82014405	 Chlorpheniramine maleate syrup 60ml"
    id: 248
}

item {
    name: "82013055	Curmin 10 capsule"
    id: 249
}

item {
    name: "82013010	 Aloegel 30g"
    id: 250
}

item {
    name: "82012410"
    id: 251
}

item {
    name: "82012105	Paracetamol 500mg GPO 1000Tablets"
    id: 252
}

item {
    name: "82012104	Paracetamol 500mg GPO 100Tablets"
    id: 253
}

item {
    name: "82012006	 Para GPO orange flavor 60ml"
    id: 254
}

item {
    name: "82011705	Metformin HCI 50x10tablets"
    id: 255
}

item {
    name: "82011505	Mixt.carminative 180ml"
    id: 256
}

item {
    name: "82011405	Mixt.carminative 450ml"
    id: 257
}

item {
    name: "82010905	Stomachic mixture 450ml"
    id: 258
}

item {
    name: "82010610	 Betamethasone-N cream 15g"
    id: 259
}

item {
    name: "82010605	Betamethasone-N cream 5g"
    id: 260
}

item {
    name: "81011603	Emulax milk of magnesia 240 ml"
    id: 261
}

item {
    name: "25021400	Avafast180mg"
    id: 262
}

item {
    name: "81011210-1   BROWN MIXTURE SOL 120CC 12BT"
    id: 263
}

item {
    name: "81011110	 Cold Syrup snake brand 60ml"
    id: 264
}

item {
    name: "81010910	 BABY COUGH 60ML 12BT"
    id: 265
}

item {
    name: "81010802-1   SNAKE BRAND SPORT OIL 30CC 12BT"
    id: 266
}

item {
    name: "81010705-1	  SNAKE BRAND MEDICATED OIL 30CC 12BT"
    id: 267
}

item {
    name: "81010205	Emulax bisacodyl 1000tablets"
    id: 268
}

item {
    name: "81010204	Emulax bisacodyl 100tablets"
    id: 269
}

item {
    name: "80041210	 3M nexcare coldhot Mini size s"
    id: 270
}

item {
    name: "80041205	 3M nexcare cold/hot pack 10x25cm"
    id: 271
}

item {
    name: "80040805	NEXCARE 3M Transpore 1incx5yard"
    id: 272
}

item {
    name: "80040705	NEXCARE 3M Transpore 1incx1.5yard"
    id: 273
}

item {
    name: "80040603	3M NEXCARE Transpore 1/2incx1.5yard"
    id: 274
}

item {
    name: "80011616	BANNER PLUS(G) 100CAP-2013"
    id: 275
}

item {
    name: "80011608	BANNER PROTEIN 100CAP-2013"
    id: 276
}

item {
    name: "80010805	BOTAN WHITE BOX 24/BOX"
    id: 277
}

item {
    name: "80010602	UTAITIP 6CC ROLL-ON"
    id: 278
}

item {
    name: "80010410	YATARD4 450CC"
    id: 279
}

item {
    name: "80010405	YATARD4 300CC MEDIUM"
    id: 280
}

item {
    name: "78021905	Moringa Herbal one 100 Capsule"
    id: 281
}

item {
    name: "78021605	Compound pet sang khat 100 capsule"
    id: 282
}

item {
    name: "78021506 	Senna leaf Ouayun 100 capsules"
    id: 283
}

item {
    name: "78021505	Senna leaf Ouayun 30 capsules"
    id: 284
}

item {
    name: "78020810"
    id: 285
}

item {
    name: "78020805"
    id: 286
}

item {
    name: "78020605"
    id: 287
}

item {
    name: "78020510	Seowtzton"
    id: 288
}

item {
    name: "78020405"
    id: 289
}

item {
    name: "78020317"
    id: 290
}

item {
    name: "78020315"
    id: 291
}

item {
    name: "78020310"
    id: 292
}

item {
    name: "78020205"
    id: 293
}

item {
    name: "78020110"
    id: 294
}

item {
    name: "78019110	 Piroxicam 20mg"
    id: 295
}

item {
    name: "78016010	Levoflox Cravit tab 500mg 5tablets"
    id: 296
}

item {
    name: "78015206	Scully anti-lice shampoo 100ml"
    id: 297
}

item {
    name: "78015204	scully anti lice shampoo 20ml"
    id: 298
}

item {
    name: "78015203	Soffell mosquito repellent lotion 70ml"
    id: 299
}

item {
    name: "78015202	Soffell mosquito repellent lotion 60ml"
    id: 300
}

item {
    name: "78013111	  Amela-Ex 30 ml"
    id: 301
}

item {
    name: "78012810	Greater Glucosamine 1500mg 30sachets"
    id: 302
}

item {
    name: "78012618"
    id: 303
}

item {
    name: "78012617	 I Colic 60CC"
    id: 304
}

item {
    name: "78012616"
    id: 305
}

item {
    name: "78012611	 I Colic"
    id: 306
}

item {
    name: "78012510	 MUCOLID"
    id: 307
}

item {
    name: "78012505	Mubroxol syrup ambroxol 60ml"
    id: 308
}

item {
    name: "78012503	 Mucolid junior ambroxol 60ml"
    id: 309
}

item {
    name: "78012405	BLACKMORS"
    id: 310
}

item {
    name: "78012306	Mysoven granules 200 60sachets"
    id: 311
}

item {
    name: "78012305	mysoven granules 100 mg 60 sachets"
    id: 312
}

item {
    name: "78012110	Fungider cream 10g"
    id: 313
}

item {
    name: "78012105	 Fungiderm-b cream 5g"
    id: 314
}

item {
    name: "78010660	Bethasone cream 15g"
    id: 315
}

item {
    name: "05030604	SALINE KARE 200 ml."
    id: 316
}

item {
    name: "78010610	 Bethasone-N cream 15 g"
    id: 317
}

item {
    name: "78010205	Uralyt-U 280g"
    id: 318
}

item {
    name: "78010112	Reparil-Gel N 40g"
    id: 319
}

item {
    name: "78010110	Reparil-Gel N 20g"
    id: 320
}

item {
    name: "77021205	 B.M. baby cough syrup 60ml"
    id: 321
}

item {
    name: "77020705-1   Supim 60 ml"
    id: 322
}

item {
    name: "77020610 	Sulidine tablets CP 10x10 tablets"
    id: 323
}

item {
    name: "77020510	SERMOROL 60ml"
    id: 324
}

item {
    name: "77020405-1"
    id: 325
}

item {
    name: "77010305 	bergamot delicate shampoo 50 ml"
    id: 326
}

item {
    name: "77010110	  bergamot hair tonic reduces hair loss 100 ml"
    id: 327
}

item {
    name: "75060705	 Dechamp 20 g"
    id: 328
}

item {
    name: "75060305-1	  Ya-hom powder five pagodas brand"
    id: 329
}

item {
    name: "75060205-1     Ya-hom powder five pagodas brand"
    id: 330
}

item {
    name: "75010120	 Takabb plum anti-cough pill"
    id: 331
}

item {
    name: "75010115	 Takabb lemongrass anti-cough pill"
    id: 332
}

item {
    name: "75010110	 Takabb mint anti-cough pill"
    id: 333
}

item {
    name: "74011603	Chom Shampoo Hair Colorc"
    id: 334
}

item {
    name: "74010410	MANOPROVIT 70B tablets"
    id: 335
}

item {
    name: "74010405	 Manoprovit Syrup 3 oz."
    id: 336
}

item {
    name: "74010305	Skindure soap Original 60 g"
    id: 337
}

item {
    name: "01010210	Daonil Glibenclamide 5mg 10 blisters x 10tablets"
    id: 338
}

item {
    name: "01010810	 Trental 400mg/Pentoxifytlne 10x10 tablets"
    id: 339
}

item {
    name: "01011410	TOPIFRAM CRM 15G"
    id: 340
}

item {
    name: "01012007	Sofradex Ear/Eye Drops 8mg"
    id: 341
}

item {
    name: "01012615	Telfast 180mg 1x10 tablets"
    id: 342
}

item {
    name: "01012705	Amaryl 2mg 12x10 tablets"
    id: 343
}

item {
    name: "38010405	Mycosamthong syrup 40 ml"
    id: 344
}

item {
    name: "38010506	S.M. OTO EAR DROPS 5CC"
    id: 345
}

item {
    name: "38010605	FLUIMUCIL GRANULES 100MG 30SACHET"
    id: 346
}

item {
    name: "38010607	FLUIMUCIL GRANULES 200MG 60SACHET"
    id: 347
}

item {
    name: "38010608	  FLUIMUCIL A 600MG 1X10TAB"
    id: 348
}

item {
    name: "38020105	TC-MYCIN 10capsules"
    id: 349
}

item {
    name: "38020106	  TC-Mycin500 10capsules"
    id: 350
}

item {
    name: "38020205	 TC- Mycin 10g"
    id: 351
}

item {
    name: "38020405	N-Zen Gel 30g"
    id: 352
}

item {
    name: "38020505	I-COF Carbocysteine 375mg 25x10 tablets"
    id: 353
}

item {
    name: "38020510	 I-COF Kid Cherry 60ml"
    id: 354
}

item {
    name: "38020520	 Mizzi lip balm 4g"
    id: 355
}

item {
    name: "38020521	Mizi collagen 4g"
    id: 356
}

item {
    name: "38020905	 Lonna Gel peppermint flavour 1g"
    id: 357
}

item {
    name: "38020910	 Lonna Gel peppermint flavour 5g"
    id: 358
}

item {
    name: "38020915	Lonna Gel orange flavour 5g"
    id: 359
}

item {
    name: "38020920	 Lonna Gel orange flavour 1g"
    id: 360
}

item {
    name: "38030405	Theolin 1000 tablets"
    id: 361
}

item {
    name: "38040305	Mantil 500tablets"
    id: 362
}

item {
    name: "38040504	 Vita-c vitamin C 30tablets"
    id: 363
}

item {
    name: "38040506	Vit-C pineapple 30tablets"
    id: 364
}

item {
    name: "38040510	Vita-c Grape flavor 1000tablets"
    id: 365
}

item {
    name: "38040516	Vita-c Grape flavor 30tablets"
    id: 366
}

item {
    name: "38041105	 Roxycan-forte 10capsules"
    id: 367
}

item {
    name: "38041915	HYDROGEN 60CC"
    id: 368
}

item {
    name: "38042205	Myda-B 5g"
    id: 369
}

item {
    name: "38042505	T.v.lone Lotion 30 ml"
    id: 370
}

item {
    name: "38043105	 Cough Syrup Iyara Ma-weang 60 ml"
    id: 371
}

item {
    name: "38060905	 LM-500 paracetamol 1000Tablets"
    id: 372
}

item {
    name: "40010405	Tiffyrub 6g"
    id: 373
}

item {
    name: "40010505	Tiffyrub 20 g"
    id: 374
}

item {
    name: "40011001	 Sara drops 15 ml"
    id: 375
}

item {
    name: "40011002	Sara for children grape flavour 60ml"
    id: 376
}

item {
    name: "40011005	Sara grenadine 60 ml"
    id: 377
}

item {
    name: "40011305	Sara 100s"
    id: 378
}

item {
    name: "40011315	AROMATIC SPIRIT AMMONIA 30ML 12"
    id: 379
}

item {
    name: "40011420	Sara 500mg 100 tablets"
    id: 380
}

item {
    name: "40011430	Sara cold PL 4tablets"
    id: 381
}

item {
    name: "40011605	Antacil 50x10 tablets"
    id: 382
}

item {
    name: "40011705-1	    Antacil Gel 240ml"
    id: 383
}

item {
    name: "40011805	Antacil Gel 450ml"
    id: 384
}

item {
    name: "40013005	Neotica 10 tablets"
    id: 385
}

item {
    name: "40013010	Neotica 20 mg 10 tablets"
    id: 386
}

item {
    name: "40014920	fespa 500 mg 10tablets"
    id: 387
}

item {
    name: "40015410	Anpuzz520 10tablets"
    id: 388
}

item {
    name: "02102503	Johnson Reach Mint Waxed 55"
    id: 389
}

item {
    name: "03010807	Andriol Testocaps"
    id: 390
}

item {
    name: "03020205	 Aureomycin Chlortetrcycline HCI Antibiotic Ointment3% 5g"
    id: 391
}

item {
    name: "03020305	Aureomycin 3g"
    id: 392
}

item {
    name: "03031105	 Ganaton 50mg 10tablets"
    id: 393
}

item {
    name: "03040305	ESSAVEN CAP 10X10FOIL"
    id: 394
}

item {
    name: "03051306	Co-Diovan 160/12.5mg"
    id: 395
}

item {
    name: "03051307	Co-Diovan 160/25mg"
    id: 396
}

item {
    name: "03060405	 LACTACYD WOMEN HYGIENE 150ML TH"
    id: 397
}

item {
    name: "03060408	LACTACYD NATURAL CARE 60ML TH"
    id: 398
}

item {
    name: "40016610	 dermaheu cream 15 g"
    id: 399
}

item {
    name: "03060411	YAMONG TRASUA HR 30 G NEW"
    id: 400
}

item {
    name: "40016615	dermaheu cream 25 g"
    id: 401
}

item {
    name: "03060415	LACTACYD SOFT AND SILKY 60ML TH2017"
    id: 402
}

item {
    name: "40012005	 IYAFIN 4tablets"
    id: 403
}

item {
    name: "03061505	Synalar-N cream 15g"
    id: 404
}

item {
    name: "40012010	 Iyafin 1000 tablets"
    id: 405
}

item {
    name: "40012400	Inhaler Khun luang"
    id: 406
}

item {
    name: "40012405	Jeny F.M.P. 28 tablets"
    id: 407
}

item {
    name: "40012505	canasone c.b. 5g"
    id: 408
}

item {
    name: "40012605	BOWA GEL"
    id: 409
}

item {
    name: "03070405	 Diprotop Ointment 5g"
    id: 410
}

item {
    name: "03071105	BUSCOPAN TABLET 10MG BLISTER 5X10X10"
    id: 411
}

item {
    name: "03071106	Diprosone Cream 15g"
    id: 412
}

item {
    name: "40012805	 IYAFIN JUNIOR 30ml"
    id: 413
}

item {
    name: "40012905	IYAFIN JUNIOR 60ml"
    id: 414
}

item {
    name: "03071305	Diprodalic Ointment 15g"
    id: 415
}

item {
    name: "40013605	Coccila 30 ml"
    id: 416
}

item {
    name: "40013705	 Coccola 60 ml"
    id: 417
}

item {
    name: "40014005	antergan 5 g"
    id: 418
}

item {
    name: "40014105	Antergan cream 10g"
    id: 419
}

item {
    name: "40014305	Benda suspension Mixed Fruit flavour 30 ml"
    id: 420
}

item {
    name: "40014405	  Benda500 1tablets"
    id: 421
}

item {
    name: "40014705	Cisteine 60 ml"
    id: 422
}

item {
    name: "40014710	Cisteine 60 ml"
    id: 423
}

item {
    name: "40014807	Dioxzye Mint Flavour 10x10tablets"
    id: 424
}

item {
    name: "40014808	DIOXZYE"
    id: 425
}

item {
    name: "40015105	Diclofenac sodium 25 mg"
    id: 426
}

item {
    name: "40015505	Preme nobu natural c white 7g"
    id: 427
}

item {
    name: "40015510	 Preme nobu natural c white 15g"
    id: 428
}

item {
    name: "40020205	TRAMIC 500/Tranexamic acid 500 mg 10x10cap"
    id: 429
}

item {
    name: "40020305	Cloxa T.O. 250mg 1000tablets"
    id: 430
}

item {
    name: "40020306	CLOKZA T.O. 500mg 500tablets"
    id: 431
}

item {
    name: "40020310	 Diclocillin 250 mg 500tablets"
    id: 432
}

item {
    name: "40020311	DicloSilline 500mg 250tablets"
    id: 433
}

item {
    name: "40020315	SUDOCREM SKIN CARE CREAM 60G (N)"
    id: 434
}

item {
    name: "40020505	Amoxy T.O. 250mg 1000tablets"
    id: 435
}

item {
    name: "40020609	Amoxi T.O. 500mg 50x10tablets"
    id: 436
}

item {
    name: "40020606	Amoxy T.O.500mg 500"
    id: 437
}

item {
    name: "40020610	 Amoxi T.O. 50mg 50x10tablets"
    id: 438
}

item {
    name: "40021305	Ninazol 10x10tablets"
    id: 439
}

item {
    name: "40021306	 Canazol cream 450 g"
    id: 440
}

item {
    name: "40021310	ZIMMEX TAB 20MG 3X10/BOX (O)"
    id: 441
}

item {
    name: "40021505	Betosone cream 450g"
    id: 442
}

item {
    name: "40021605	Betosone-EN cream 450 g"
    id: 443
}

item {
    name: "40021612	Canazol cream 5g"
    id: 444
}

item {
    name: "40021613	CANAZOL-Be Cream 15g"
    id: 445
}

item {
    name: "40021620	Canazol cream 5 g"
    id: 446
}

item {
    name: "40021701	Gentaderm cream 5g"
    id: 447
}

item {
    name: "40021703	 VIROGON CREAM 1G"
    id: 448
}

item {
    name: "40021705	KELAPLUS 5g"
    id: 449
}

item {
    name: "40021707	ZIMMEX TAB 10MG 3X10/BOX (O)"
    id: 450
}

item {
    name: "40021915	Selfide selenium 30ml"
    id: 451
}

item {
    name: "40021916	 Selfide selenium 60ml"
    id: 452
}

item {
    name: "40021918	Selfide selenium 120ml"
    id: 453
}

item {
    name: "40022205	 Cardeloc 500tablets"
    id: 454
}

item {
    name: "40022206	CARDELOC 50x10tablets"
    id: 455
}

item {
    name: "40022405	 Muflex Tablets 50x10 tablets"
    id: 456
}

item {
    name: "40022705	SPORIDIN SUSPENSION 125MG/5ML 60ML"
    id: 457
}

item {
    name: "40022905	Cardenol 10 mg 1000mg"
    id: 458
}

item {
    name: "40023005	 Cardenol 40mg 1000 tablets"
    id: 459
}

item {
    name: "40023405	taraxin 1000tablets"
    id: 460
}

item {
    name: "40023406	TO Taraxin syrup 50ml"
    id: 461
}

item {
    name: "40023505	Toloxin Digoxin 0.25mg 100x10Tablets"
    id: 462
}

item {
    name: "40023906	BACOTAN FC 10 Mg. 100*1"
    id: 463
}

item {
    name: "40024503	 Ditap Infant 15 ml"
    id: 464
}

item {
    name: "40024505	  Ditap syrup 60 ml"
    id: 465
}

item {
    name: "40024705	Comox suspension 60 ml"
    id: 466
}

item {
    name: "74010210	 Skindure cream Miconazole Nitrate 10 g"
    id: 467
}

item {
    name: "74010110	Lamthong skindure 20 ml"
    id: 468
}

item {
    name: "73060905	 K-Y GEL LUBRIFICANT STERILE 42G 48/CASE"
    id: 469
}

item {
    name: "03072110	Elomet Cream 0.1% 15g"
    id: 470
}

item {
    name: "03072505	Nasonex 60 doses"
    id: 471
}

item {
    name: "03080310	NATRILIX SR TAB 1.5MG 30"
    id: 472
}

item {
    name: "03080505	DIAMICRON TAB 80MG 100"
    id: 473
}

item {
    name: "03080606	PERNAZENE-OXY NASAL SPRAY 75MG 15ML"
    id: 474
}

item {
    name: "03081005	Synflex Naproxen sodium 275mg 10x6tablets"
    id: 475
}

item {
    name: "03081606	VASTAREL MR TAB 35MG 60"
    id: 476
}

item {
    name: "03090155	Curam 156,25mg/5ml/60ml"
    id: 477
}

item {
    name: "03090156	 Curam forte 312mg/60ml"
    id: 478
}

item {
    name: "03090158	Curam 625mg 12 tablets"
    id: 479
}

item {
    name: "03090159	Curam 1000mg 12tablets"
    id: 480
}

item {
    name: "08020107	  Betalol 10mg 100x10Tablets"
    id: 481
}

item {
    name: "03090209	 Meptin syrup 60ml"
    id: 482
}

item {
    name: "03090251	Perskindol Classic Gel 100ml"
    id: 483
}

item {
    name: "08020405	Xanidine 150mg 10x10tablets"
    id: 484
}

item {
    name: "03090253	Perskindol Cool Gel 100ml"
    id: 485
}

item {
    name: "08020506	 Mirax-M 100x10tablets"
    id: 486
}

item {
    name: "03090254	Perskindol Classic Spray 150g"
    id: 487
}

item {
    name: "03090255	Perskindol Cool Spray 250ml"
    id: 488
}

item {
    name: "03091405	Kamilosan M 15ml"
    id: 489
}

item {
    name: "03091506	Systral Cream 25g"
    id: 490
}

item {
    name: "08021008	Prenolol 25mg 50x10 tablets /Berlin"
    id: 491
}

item {
    name: "08021010	Prenolol 50mg 10*10 tablets"
    id: 492
}

item {
    name: "08021110	Prenolol 100mg10*10tablets"
    id: 493
}

item {
    name: "08021303	Anapril 5mg 10x10 tablets"
    id: 494
}

item {
    name: "90200115	 Coconut Oil root 100% 1000CC"
    id: 495
}

item {
    name: "08021505	Nelapine 5mg 10x10tablets"
    id: 496
}

item {
    name: "08021605	Nelapine 10mg 10x10tablets"
    id: 497
}

item {
    name: "08021606	Nelapine SR 20mg 3x10tablets"
    id: 498
}

item {
    name: "08021705	Amlopine 5mg/10*1tablets"
    id: 499
}

item {
    name: "08021706	Amlodipine 10 mg"
    id: 500
}

item {
    name: "BG SIK /BERLIN"
    id: 501
}

item {
    name: "08022205	Duspatin 135mg/10x10tablets"
    id: 502
}

item {
    name: "08022304	Hidil 300mg 10x10tablets"
    id: 503
}

item {
    name: "08022305	 Hidil 600mg 10*10tablets"
    id: 504
}

item {
    name: "08022404	Mucilin SF 10sachets"
    id: 505
}

item {
    name: "08022405	 Mucilin 100g"
    id: 506
}

item {
    name: "08022406	 MUCILLIN 400 g"
    id: 507
}

item {
    name: "08023003	Bestatin 10mg 10x10tablets"
    id: 508
}

item {
    name: "08023006	 Bestatin 20mg 10x10tablets"
    id: 509
}

item {
    name: "08023005	Bestatin 40mg 10x10 tablets"
    id: 510
}

item {
    name: "90200009	propo coco coconut oil 1000ml"
    id: 511
}

item {
    name: "03101116	 Mega II Care 30 capsule"
    id: 512
}

item {
    name: "nac long"
    id: 513
}

item {
    name: "04010605	 Anorsia 60ml"
    id: 514
}

item {
    name: "04010905	Asiatapp Infant Drops 15 ml"
    id: 515
}

item {
    name: "23030108 	napex syrup 60ml"
    id: 516
}

item {
    name: "04020105 	Kenya Gel 500 tabtels"
    id: 517
}

item {
    name: "colistin"
    id: 518
}

item {
    name: "05010105	Tetracycline hydrochlorids 250mg 1000tablets"
    id: 519
}

item {
    name: "05010110	Tetracycline hydrochlorids 250mg 1000tablets"
    id: 520
}

item {
    name: "05010112	 Ketoral 250 Tablets"
    id: 521
}

item {
    name: "05010207	Paracetamol 500mg 1000Tablets"
    id: 522
}

item {
    name: "05010505	Oxytetracycling 1000Capsule"
    id: 523
}

item {
    name: "05010905	Asumol 1000Tablets"
    id: 524
}

item {
    name: "05010906	Asumol 1000Tablets"
    id: 525
}

item {
    name: "05020105	Dimen Hydrinate 1000 tablets"
    id: 526
}

item {
    name: "05031905	Glucose 50% 10ml"
    id: 527
}

item {
    name: "05032105	 Ampavit Vitamin B12 1000mcg 1mlx10amp"
    id: 528
}

item {
    name: "06061805	Cardiprin Tablets 100mg 30 tablets"
    id: 529
}

item {
    name: "07020411	SS MULTIVIT LYSINE 100ML WITH BACK CARD"
    id: 530
}

item {
    name: "05032205	Ampavit Vitamin B12 1000mcg/ 10ml"
    id: 531
}

item {
    name: "05032705	 CHLORPHENIRAMINE INGJECTION 1 ml 10ampoules"
    id: 532
}

item {
    name: "05050105	Sodium Chloride 0.9%/PIC"
    id: 533
}

item {
    name: "Dexaltin"
    id: 534
}

item {
    name: "Dexaltin 5g"
    id: 535
}

item {
    name: "06000406	BRAND Essence of chicken 45ml"
    id: 536
}

item {
    name: "13020106	ID CORDY Cordyceps Extradct 1490.-"
    id: 537
}

item {
    name: "06000505	 BRAND Essence of chicken 70ml"
    id: 538
}

item {
    name: "06000601	 Brand Junior Alpha Mynd/Fish Oil and Lecithin 42ml"
    id: 539
}

item {
    name: "brand"
    id: 540
}

item {
    name: "06000803	brand"
    id: 541
}

item {
    name: "06000806	Brands genuine bird nest xylitol 42ml"
    id: 542
}

item {
    name: "06000905	 BRAND genuine bird nest 42 ml"
    id: 543
}

item {
    name: "06000908	Brand veta berry essence concentrate 42 mL"
    id: 544
}

item {
    name: "06000910	VOLTAREN TAB 25MG 3X10/BOX"
    id: 545
}

item {
    name: "06001025	brands essence of mushroom 65 ml"
    id: 546
}

item {
    name: "06001035	 Brands Calcium 600+Soy Germ 60tablets"
    id: 547
}

item {
    name: "06010205	 Nizoral cream 20g"
    id: 548
}

item {
    name: "Nizoral 200mg"
    id: 549
}

item {
    name: "06010505	 Nizoral SHAMPOO KETOCONAZOLE 2% 50 ml"
    id: 550
}

item {
    name: "06010705	 Nizoral SHAMPOO KETOCONAZOLE 2% 100 ML."
    id: 551
}

item {
    name: "06010805	Daktarin cream 5g"
    id: 552
}

item {
    name: "06010905	Daktarin cream 15g"
    id: 553
}

item {
    name: "06011405	Tylenal 60ml"
    id: 554
}

item {
    name: "06011406	Tylenal 15ml"
    id: 555
}

item {
    name: "06011515	Tylenol Tablets 500mg 100Tablets"
    id: 556
}

item {
    name: "06011517	 TYLENOL 8 HOUR TAB 650MG 10/BOX"
    id: 557
}

item {
    name: "06011705	Motiluim 30 ml"
    id: 558
}

item {
    name: "08012512	Cotton pads V-care 50g"
    id: 559
}

item {
    name: "06012505	Sporal 4capsule"
    id: 560
}

item {
    name: "38043706	Polar Wipe Purified Saline Plus Activ Polar"
    id: 561
}

item {
    name: "06012705	 Retin-A cream 10g"
    id: 562
}

item {
    name: "25021011	I-herb brand 60ml"
    id: 563
}

item {
    name: "06020106	Hirudoid Cream 7g"
    id: 564
}

item {
    name: "06020305	HIRUDOID CREAM 40G NEW PACK"
    id: 565
}

item {
    name: "Hirudoid forte"
    id: 566
}

item {
    name: "06201105	 Ezerra extra 30ml."
    id: 567
}

item {
    name: "06020605 	Hirudoid forte 40g"
    id: 568
}

item {
    name: "06020620	  HIRUDOID MILD CREAM 50 G"
    id: 569
}

item {
    name: "06021005	 ELMETACIN SPRAY 50 ML"
    id: 570
}

item {
    name: "90200206	chrra coco 500ml"
    id: 571
}

item {
    name: "06030305	KWAN LOONG OIL 15ML NEW"
    id: 572
}

item {
    name: "06030410	 Kwang Loong H.R. 28ml"
    id: 573
}

item {
    name: "06030505	 Kwang Loong H.R. 57ml"
    id: 574
}

item {
    name: "06031001	Tiger Balm red HR 10g"
    id: 575
}

item {
    name: "06031002	 Tiger Balm white HR 10g"
    id: 576
}

item {
    name: "06031010  	TIGER BALM red 19.4g"
    id: 577
}

item {
    name: "06031110	Tiger Balm Ointment-HR 19.4 g"
    id: 578
}

item {
    name: "06031205	Tiger Balm red HR 30g"
    id: 579
}

item {
    name: "06031305	Tiger Balm white HR 30g"
    id: 580
}

item {
    name: "06031705	Tiger Balm /Medicated Plaster Cool 7*10cm"
    id: 581
}

item {
    name: "08023102	Caraten 6.25 mg. 10*10tablets"
    id: 582
}

item {
    name: "08023103	Caraten 12.5mg 10*10 tablets"
    id: 583
}

item {
    name: "08023105	Caraten 25 mg 10x10 tablets"
    id: 584
}

item {
    name: "08023505	 Lanzaar 50mg 30tablets"
    id: 585
}

item {
    name: "08023605	Apolets 75mg 30capsules"
    id: 586
}

item {
    name: "08030105	 MUCOSOLVAN TAB 30MG 50X10/BOX M36-SA"
    id: 587
}

item {
    name: "08030305	BISOLVON TAB 8MG 50X10/BOX M36-SA"
    id: 588
}

item {
    name: "11010905	Gripe water 148ml"
    id: 589
}

item {
    name: "08030405	Bisolvon Elixir 60ml"
    id: 590
}

item {
    name: "08030505	Bisolvon Elixir 125ml"
    id: 591
}

item {
    name: "08030605	 BisolvonEx syrup 60 ml"
    id: 592
}

item {
    name: "08030705	BisolvonEX 125ml."
    id: 593
}

item {
    name: "08031205	BUSCOPAN TAB 10MG 10X10/BOX M36-SA"
    id: 594
}

item {
    name: "08031405	 DULCOLAX TAB 5MG 50X10BL M24-SA"
    id: 595
}

item {
    name: "08031607	Dulcolax suppository 10 suppositories"
    id: 596
}

item {
    name: "08032210	PHARMATON KIDDI SYRUP 100ML 24M-SA"
    id: 597
}

item {
    name: "08032504	PHARMATON CAP 30/BOX M36-SA"
    id: 598
}

item {
    name: "08032505	PHARMATON CAP 100/BOX M36-SA"
    id: 599
}

item {
    name: "08032905	Berodual MA 10 ml"
    id: 600
}

item {
    name: "08033004	 Berodual Forte UDV 4CC"
    id: 601
}

item {
    name: "08033305	Mobic 7.5mg/10x10tablels"
    id: 602
}

item {
    name: "08033310	  Mobic 15mg/10x10tablels"
    id: 603
}

item {
    name: "08040205	Faire romance 3 condoms"
    id: 604
}

item {
    name: "08050105	Domperdone 500 tablets"
    id: 605
}

item {
    name: "08050505	 Furide 500tablets"
    id: 606
}

item {
    name: "08050705	 Berclomine syrup 60ml"
    id: 607
}

item {
    name: "08050805	 Berclomin tab 50x10tablets"
    id: 608
}

item {
    name: "08051005	Tacinol 0.1 % 5g"
    id: 609
}

item {
    name: "08051205	Tara-Plus Cream 5g"
    id: 610
}

item {
    name: "08051305	Tara-Plus Cream 500gm"
    id: 611
}

